# Generated by Django 5.1.1 on 2025-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_myprofile_alter_message_id_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='nickname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
