# Generated by Django 5.1.1 on 2025-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='room_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
