# Generated by Django 5.1.1 on 2025-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_myprofile_room_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='myname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='room_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
