# Generated by Django 5.1.1 on 2025-05-12 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_room_myname'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='birthday',
            field=models.DateField(default=datetime.date(1950, 1, 1), max_length=100),
        ),
    ]
